spring:
  kafka:
    bootstrap-servers: localhost:9092
    portion-topic: "portions"
    consumer:
      auto-offset-reset: earliest
      groupId: "portion"

  datasource:
    url: jdbc:postgresql://localhost:5434/portions
    username: postgres
    password: mcpmwC8gGwVKr4Q9xCKZEzEgS

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

    liquibase:
      change-log: classpath:/db/changelog/db.changelog-master.yaml
      enabled: true
server:
  port: 8083


